### ISSUE TITLE
Unable to install dependencies

### ISSUE THREAD

**Issue by WillJW** [andrefigueira/Vine#1]
I'm trying to install this via Composer, but keep getting the following error:

![image](https://cloud.githubusercontent.com/assets/1878977/9465621/138f4ef2-4b26-11e5-8b53-4fa64c1788f8.png)

Any help with this is appreciated.

**Comment by andrefigueira** [comment]
Ah! I know what that is, 2 secs and I'll sort it out.

**Comment by andrefigueira** [comment]
@WillJW All fixed! Just make sure you get package 0.0.4 instead of 0.0.3.

**Comment by WillJW** [comment]
Outstanding response time. Thank you, sir!

![tumblr_inline_n05gzy2wmz1s4ovc9](https://cloud.githubusercontent.com/assets/1878977/9465902/89cafce0-4b28-11e5-8e3e-4dcd880f2894.gif)

**Comment by andrefigueira** [comment]
@WillJW You're most welcome, the merits of OCD :P
